- name: setup flanneld
  copy: src=flanneld owner=root group=root dest=/etc/sysconfig/flanneld

- name: make docker service directory
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: copy systemd flanneld file
  copy: src=10-flanneld-network.conf owner=root group=root dest=/etc/systemd/system/docker.service.d

- name: setup kubelet
  template:
    src: kubelet.j2
    dest: /etc/kubernetes/kubelet
    owner: root
    group: root
    mode: 0644
  when: provider == "libvirt"

- name: setup kubelet
  template:
    src: kubelet.vb.j2
    dest: /etc/kubernetes/kubelet
    owner: root
    group: root
    mode: 0644
  when: provider == "virtualbox"

- name: set master location
  copy: src=config owner=root group=root dest=/etc/kubernetes/config

- name: restart systemd
  command: systemctl daemon-reload

- name: enable kube services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - flanneld
    - kubelet
    - kube-proxy

- name: move ssh port to 8022
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#Port 22" line="Port 8022"

- name: wait until minion has registered
  command: sleep 10

- name: remove label minion
  command: kubectl -s http://192.168.10.90:8080 label node {{ansible_eth1.ipv4.address}} name-
  when: provider == "libvirt"

- name: label minion
  command: kubectl -s http://192.168.10.90:8080 label node {{ansible_eth1.ipv4.address}} name=worker-{{ansible_eth1.ipv4.address.split('.')[3]}}
  when: provider == "libvirt"

- name: remove label minion
  command: kubectl -s http://192.168.10.90:8080 label node {{ansible_enp0s8.ipv4.address}} name-
  when: provider == "virtualbox"

- name: label minion
  command: kubectl -s http://192.168.10.90:8080 label node {{ansible_enp0s8.ipv4.address}} name=worker-{{ansible_enp0s8.ipv4.address.split('.')[3]}}
  when: provider == "virtualbox"
