- hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- hosts: master
  become: yes
  become_method: sudo
  roles:
    - kub_master

- hosts: minions
  become: yes
  become_method: sudo
  roles:
    - kub_minion

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - upgrade
