- name: setup etcd
  copy: src=etcd.conf owner=root group=root dest=/etc/etcd

- name: copy kub configuration
  copy: src={{ item }} owner=root group=root dest=/etc/kubernetes mode=644
  with_items:
    - config
    - apiserver
    - kubelet

- name: copy flanneld configuration
  copy: src=flanneld-conf.json dest=/home/vagrant owner=vagrant group=vagrant

- name: copy setup_gluster
  copy: src=setup_gluster.sh dest=/home/vagrant owner=vagrant group=vagrant mode=755

- name: copy pods
  copy: src=pods dest=/home/vagrant owner=vagrant group=vagrant directory_mode=755 mode=644

- name: get heketi client
  command: curl -L -O https://github.com/heketi/heketi/releases/download/1.0.2/heketi-1.0.2-release-1.0.0.linux.amd64.tar.gz chdir=/home/vagrant

- name: unarchive heketi client
  unarchive: src=/home/vagrant/heketi-1.0.2-release-1.0.0.linux.amd64.tar.gz copy=no dest=/home/vagrant owner=vagrant group=vagrant

- name: mv client
  command: mv heketi/heketi-cli /home/vagrant chdir=/home/vagrant

- name: change permissions
  command: chown vagrant:vagrant heketi-cli chdir=/home/vagrant

- name: remove files
  command: rm -fr heketi-1.0.2-release-1.0.0.linux.amd64.tar.gz heketi

- name: enable kube services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: setup flannel config in etcd
  command: chdir=/home/vagrant curl -L http://localhost:2379/v2/keys/atomic01/network/config -XPUT --data-urlencode value@flanneld-conf.json 
