apiVersion: v1
kind: Pod
metadata:
  name: gluster-3
  labels:
    name: gluster-3
spec:
  hostNetwork: true
  nodeSelector:
    name: worker-102
  containers:
    - name: glusterfs
      image: lpabon/gluster
      ports:
        - name: ssh
          containerPort: 22
      securityContext: 
        capabilities: {}
        privileged: true
      volumeMounts:
        - name: brick
          mountPath: /srv/brick
        - name: cgroups
          mountPath: /sys/fs/cgroup
          readOnly: true
  volumes:
    - name: brick
      hostPath:
        path: "/srv/brick"
    - name: cgroups
      hostPath:
        path: "/sys/fs/cgroup"
