- name: clean iptables
  command: iptables -F

- name: disable selinux
  selinux: state=disabled

- name: fix issue with eth1
  copy: src=rc.local owner=root group=root mode=755 dest=/etc/rc.d
  when: provider == "libvirt"

- name: fix issue with enp0s8
  copy: src=rc.local.vb owner=root group=root mode=755 dest=/etc/rc.d/rc.local
  when: provider == "virtualbox"

- name: configure dm_snapshot module
  copy: src=dm_snapshot.conf owner=root group=root mode=644 dest=/etc/modules-load.d
